### ISSUE TITLE
No static method getNoBackupFilesDir

### ISSUE THREAD

**Issue by lcalmejane** [Xtraball/SiberianCMS#339]
Hello i Try the Solution in IOS and Android.
And for Android i have for many emulator the same issue.
The application is launched, and crash.
I have this Message 
`07-04 15:58:26.473 6364-6473/com.dedalesoftware.mob1.androidoverview E/AndroidRuntime: FATAL EXCEPTION: pool-1-thread-4
                                                                                       Process: com.dedalesoftware.mob1.androidoverview, PID: 6364
                                                                                       java.lang.NoSuchMethodError: No static method getNoBackupFilesDir(Landroid/content/Context;)Ljava/io/File; in class Lcom/google/android/gms/common/util/zzx; or its super classes (declaration of 'com.google.android.gms.common.util.zzx' appears in /data/app/com.dedalesoftware.mob1.androidoverview-2/split_lib_dependencies_apk.apk:classes21.dex)
                                                                                           at com.google.android.gms.iid.zzd.zzeG(Unknown Source)
                                                                                           at com.google.android.gms.iid.zzd.<init>(Unknown Source)
                                                                                           at com.google.android.gms.iid.zzd.<init>(Unknown Source)
                                                                                           at com.google.android.gms.iid.InstanceID.zza(Unknown Source)
                                                                                           at com.google.android.gms.iid.InstanceID.getInstance(Unknown Source)
                                                                                           at com.adobe.phonegap.push.PushPlugin$1.run(PushPlugin.java:73)
                                                                                           at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                                           at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                                           at java.lang.Thread.run(Thread.java:818)`

**Comment by Slicit** [comment]
Please advise while testing in a real phone ;)

**Comment by lcalmejane** [comment]
same thing with a Real mobile 
`7771-7975/com.dedalesoftware.mob1.androidoverview E/AndroidRuntime: FATAL EXCEPTION: pool-2-thread-3
                                                                                       Process: com.dedalesoftware.mob1.androidoverview, PID: 7771
                                                                                       java.lang.NoSuchMethodError: No static method getNoBackupFilesDir(Landroid/content/Context;)Ljava/io/File; in class Lcom/google/android/gms/common/util/zzx; or its super classes (declaration of 'com.google.android.gms.common.util.zzx' appears in /data/app/com.dedalesoftware.mob1.androidoverview-1/split_lib_dependencies_apk.apk:classes25.dex)
                                                                                           at com.google.android.gms.iid.zzd.zzeG(Unknown Source)
                                                                                           at com.google.android.gms.iid.zzd.<init>(Unknown Source)
                                                                                           at com.google.android.gms.iid.zzd.<init>(Unknown Source)
                                                                                           at com.google.android.gms.iid.InstanceID.zza(Unknown Source)
                                                                                           at com.google.android.gms.iid.InstanceID.getInstance(Unknown Source)
                                                                                           at com.adobe.phonegap.push.PushPlugin$1.run(PushPlugin.java:73)
                                                                                           at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                                           at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                                           at java.lang.Thread.run(Thread.java:818)
07-05 09:57:05.904 2936-3759/? W/ActivityManager:   Force finishing activity com.dedalesoftware.mob1.androidoverview/.MainActivity`

**Comment by Slicit** [comment]
Okay thanks, seems to be an issue with the latests Android SDK versions & the com.google.android.gms:play-services-gcm version not being high enough, we will try tu update the version in a next release.

Probably 4.12.1

**Comment by Slicit** [comment]
Closing for inactivity! re-open if issue is still relevant
